import MobileNavigation from "@/components/navigation/MobileNavigation";
import "./globals.css";
import { Montserrat } from "next/font/google";
import Footer from "@/components/navigation/Footer";
import Navbar from "@/components/navigation/Navbar";

const font = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pl">
      <body className={font.className}>
        <Navbar />

        {children}

        <MobileNavigation />
        <Footer />
      </body>
    </html>
  );
}
