backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

# Uncomment local_backend when you need to develop in your local
#local_backend: true # run npx netlify-cms-proxy-server for local testing

media_folder: "static/assets"
public_folder: "/assets"

collections:
  - name: "products" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Produkty" # Used in the UI
    label_singular: "Produkt" # Used in the UI, ie: "New Post"
    description: >
      Create awesome content here.
    folder: "src/content/products"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    summary: "{{title}} — {{year}}/{{month}}/{{day}}"
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {
          label: "Template",
          name: "template",
          widget: "hidden",
          default: "blog-post",
        }
      - { label: "Title", name: "title", widget: "string", tagname: "h1" }
      - {
          label: "Ścieżka do strony",
          name: "slug",
          widget: "string",
          hint: "Rozpocznij od / oraz używaj tylko alfabetu, - i _. Unikaj polskich znaków. MUSI być unikalne.",
        }
      - {
          label: "Data publikacji",
          name: "date",
          widget: "datetime",
          dateFormat: "YYYY-MM-DD",
          timeFormat: "HH:mm",
          format: "YYYY-MM-DD HH:mm",
        }
      - {
          label: "Opis SEO",
          name: "description",
          widget: "text",
          hint: "Opis który wyświetli sie w wyszukiwarce.",
        }
      - {
          label: "Zdjęcie",
          name: "featuredImage",
          widget: "image",
          tagname: "",
        }
      - { label: "Główny opis produktu", name: "body", widget: "markdown" }
  - label: "Strony"
    name: "pages"
    files:
      - label: "Strona główna"
        name: "home"
        file: "src/content/pages/index.md"
        fields:
          - {
              label: "Template",
              name: "template",
              widget: "hidden",
              default: "index-page",
            }
          - { label: "Slug", name: "slug", widget: "hidden", default: "/" }
          - { label: "Tytył", name: "title", widget: "string" }
          - { label: "Podtytuł", name: "tagline", widget: "string" }
          - { label: "Zdjęcie", name: "featuredImage", widget: "image" }
          - { label: "Opis", name: "body", widget: "markdown" }
          - label: "Guzik"
            name: "cta"
            widget: "object"
            fields:
              - name: "ctaText"
                label: "Etykieta na przycisku"
                widget: "string"
              - name: "ctaLink"
                label: "Ścieżka gdzie ma prowadzić"
                widget: "string"
      - label: "O nas"
        name: "about"
        file: "src/content/pages/about.md"
        fields:
          - {
              label: "Template",
              name: "template",
              widget: "hidden",
              default: "about-page",
            }
          - { label: "Slug", name: "slug", widget: "hidden", default: "/about" }
          - { label: "Tytył", name: "title", widget: "string" }
          - { label: "Opis", name: "body", widget: "markdown" }
      - label: "Kontakt"
        name: "contact"
        file: "src/content/pages/contact.md"
        fields:
          - {
              label: "Template",
              name: "template",
              widget: "hidden",
              default: "contact-page",
            }
          - {
              label: "Slug",
              name: "slug",
              widget: "hidden",
              default: "/contact",
            }
          - { label: "Tytuł", name: "title", widget: "string" }
          - { label: "Opis", name: "body", widget: "markdown" }
      - label: "Polityka prywatności"
        name: "privacy-policy"
        file: "src/content/pages/privacy-policy.md"
        fields:
          - {
              label: "Template",
              name: "template",
              widget: "hidden",
              default: "privacy-policy-page",
            }
          - {
              label: "Slug",
              name: "slug",
              widget: "hidden",
              default: "/privacy-policy",
            }
          - { label: "Tytuł", name: "title", widget: "string" }
          - { label: "Treść", name: "body", widget: "markdown" }
  - name: settings
    label: Settings
    files:
      - name: general
        label: General
        file: "src/util/site.json"
        fields:
          - label: meta
            name: meta
            widget: object
            fields:
              - widget: string
                name: title
                label: Site Title
                required: true
              - widget: string
                name: titleTemplate
                label: Title Template
                default: "%s"
                required: true
              - widget: string
                name: siteUrl
                label: Website URL
                required: true
              - widget: text
                name: description
                label: Description
                default: ""
                required: false
              - widget: image
                name: image
                label: image
                default: "/assets/stackrole.png"
              - widget: image
                name: iconimage
                label: favicon
              - widget: string
                name: twitterUsername
                label: Twitter
                required: false

          - label: "Google Analytics"
            name: ga
            widget: string
            hint: "Add you tracking ID, for example UA-XXXXXXXXX-X"
